---
  version: '3.7'

  x-config:
    &secrets-config
    secrets:
      - source: ssl_crt
        target: /home/python/ssl.crt
      - source: ssl_key
        target: /home/python/ssl.key

  secrets:
    ssl_crt:
      file: ./docker/certificates/wildcard.crt
    ssl_key:
      file: ./docker/certificates/wildcard.key

  services:
    mlr-validator:
      build: .
      image: mlr-validator
      ports:
        - "6027:6027"
      volumes: 
        - ./docker/certificates/import_certs:/home/python/certificates:ro
        - ./remote-references:/home/python/remote-references:ro
      << : *secrets-config
      env_file:
        - ./docker/config.env
        - ./docker/secrets.env
    
    mlr-validator-local-dev:
      build: .
      image: mlr-validator
      network_mode: "host"
      ports:
        - "6027:6027"
      volumes: 
        - ./docker/certificates/import_certs:/home/python/certificates:ro
      << : *secrets-config
      env_file:
        - ./docker/config.env
        - ./docker/secrets.env
