import os
from setuptools import setup, find_packages


def read_requirements(filename):
    """
    Get application requirements from
    the requirements.txt file.
    :return: portal_ui Python requirements
    :rtype: list
    """
    with open(filename, 'r') as req:
        requirements = req.readlines()
    install_requires = [r.strip() for r in requirements if r.find('git+') != 0]
    return install_requires


def read(filepath):
    """
    Read the contents from a file.
    :param str filepath: path to the file to be read
    :return: file contents
    :rtype: str
    """
    with open(filepath, 'r') as f:
        content = f.read()
    return content

def identify_data_files(directory_names, exclusions=('.gitignore', '.webassets-cache')):
    """
    Recursively introspect the contents of a directory. Once the contents
    have been introspected, generate a list directories and sub-directories
    with their contents as lists.
    Any files listed in exclusions will not be included
    as a data file. Please note that the list generated by this function
    will override any exclusions defined in MANIFEST.in. This
    means that if one specifies a file to be excluded in MANIFEST.in,
    but this function includes that file as a data file, then it's
    going to be in the distributable.
    :param list directory_names: absolute or relative name to directories
    :param tuple exclusions: tuple of all the files or directories NOT to include as a data file
    :return: all contents of the directories as a list of tuples
    :rtype: list
    """
    directory_data_files = []
    for directory_name in directory_names:
        for root, dirs, files in os.walk(directory_name):
            pathnames = [os.path.abspath(os.path.join(root, filename))
                         for filename in files if not any(ex in os.path.join(root, filename) for ex in exclusions)]
            if len(pathnames) > 0:
                data_file_element = (root, pathnames)
                directory_data_files.append(data_file_element)
    return directory_data_files


requirements = read_requirements('requirements.txt')
data_files = identify_data_files(['schemas', 'references'])

setup(name='usgs_wma_mlr_validator',
      version='0.4.0dev',
      description='MLR Validator Microservice',
      author='Mary Bucknell, Andrew Yan, Dave Steinich, Zack Moore, Kathy Schoephoester',
      author_email='mlr-devs@usgs.gov',
      include_package_data=True,
      long_description =read('README.md'),
      install_requires=requirements,
      test_loader='unittest:TestLoader',
      platforms='any',
      zip_safe=False,
      py_modules=['config', 'app'],
      packages=find_packages(),
      data_files=data_files
      )
